### PR TITLE
[Client]Bug fix in util file generation

### PR DESCRIPTION
**Pull request by aneeshafedo**
Reason for bug : Conflict in file names with ballerina-graphql tool

Resolves https://github.com/ballerina-platform/openapi-tools/issues/965

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

**Review by lnash94 — APPROVED** [review]
LGTM

**Review by NipunaRanasinghe — APPROVED** [review]
@aneeshafedo @lnash94 shouldn't we have a test case for this to avoid any regression in the future? or is it disabled ATM?

**Comment by lnash94** [comment]
> @aneeshafedo @lnash94 shouldn't we have a test case for this to avoid any regression in the future? or is it disabled ATM?

We have unit tests for this, and that time it worked as expected, yeah it would be great if we can add some integration tests as well 🙂

**Comment by aneeshafedo** [comment]
> > @aneeshafedo @lnash94 shouldn't we have a test case for this to avoid any regression in the future? or is it disabled ATM?
> 
> We have unit tests for this, and that time it worked as expected, yeah it would be great if we can add some integration tests as well slightly_smiling_face

It seems that we do not have any integration tests written for client generation. Shall we add few tests for client generation to this PR or shall i send a new PR ?

**Comment by lnash94** [comment]
> > > @aneeshafedo @lnash94 shouldn't we have a test case for this to avoid any regression in the future? or is it disabled ATM?
> > 
> > 
> > We have unit tests for this, and that time it worked as expected, yeah it would be great if we can add some integration tests as well slightly_smiling_face
> 
> It seems that we do not have any integration tests written for client generation. Shall we add few tests for client generation to this PR or shall i send a new PR ?

Went through the test written and it looks good to me 🙂 , Feel these tests are most suitable to place on the ballerina distribution repo,  Because this moment we only create our distribution using our dependency except external jar azure, asyncapi, graphQL-tool and c2c. As we understood this occurs made conflict with graphQL-tool and those module we didn't pack within openapi tool cause to misdirect our test expectation. But we can have those module in distribution because it has a full distribution pack, 
therefore shall we move this test to the distribution repo [here](https://github.com/ballerina-platform/ballerina-distribution/blob/master/ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java) for getting the expected behaviour of the test? WDYT? @NipunaRanasinghe @aneeshafedo

**Comment by aneeshafedo** [comment]
> > > > @aneeshafedo @lnash94 shouldn't we have a test case for this to avoid any regression in the future? or is it disabled ATM?
> > > 
> > > 
> > > We have unit tests for this, and that time it worked as expected, yeah it would be great if we can add some integration tests as well slightly_smiling_face
> > 
> > 
> > It seems that we do not have any integration tests written for client generation. Shall we add few tests for client generation to this PR or shall i send a new PR ?
> 
> Went through the test written and it looks good to me slightly_smiling_face , Feel these tests are most suitable to place on the ballerina distribution repo, Because this moment we only create our distribution using our dependency except external jar azure, asyncapi, graphQL-tool and c2c. As we understood this occurs made conflict with graphQL-tool and those module we didn't pack within openapi tool cause to misdirect our test expectation. But we can have those module in distribution because it has a full distribution pack, therefore shall we move this test to the distribution repo [here](https://github.com/ballerina-platform/ballerina-distribution/blob/master/ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java) for getting the expected behaviour of the test? WDYT? @NipunaRanasinghe @aneeshafedo

I think this would be the best solution to catch these kind of issues at the first place, if its possible to implement

**Comment by NipunaRanasinghe** [comment]
> > > > @aneeshafedo @lnash94 shouldn't we have a test case for this to avoid any regression in the future? or is it disabled ATM?
> > > 
> > > 
> > > We have unit tests for this, and that time it worked as expected, yeah it would be great if we can add some integration tests as well slightly_smiling_face
> > 
> > 
> > It seems that we do not have any integration tests written for client generation. Shall we add few tests for client generation to this PR or shall i send a new PR ?
> 
> Went through the test written and it looks good to me 🙂 , Feel these tests are most suitable to place on the ballerina distribution repo, Because this moment we only create our distribution using our dependency except external jar azure, asyncapi, graphQL-tool and c2c. As we understood this occurs made conflict with graphQL-tool and those module we didn't pack within openapi tool cause to misdirect our test expectation. But we can have those module in distribution because it has a full distribution pack, therefore shall we move this test to the distribution repo [here](https://github.com/ballerina-platform/ballerina-distribution/blob/master/ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java) for getting the expected behaviour of the test? WDYT? @NipunaRanasinghe @aneeshafedo

Yeah moving these tests to the distribution repo will be a better option. +1

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

**Comment by aneeshafedo** [comment]
@lnash94 @NipunaRanasinghe removed client generation integration tests

**Pull request merged**
