### PR TITLE
[1.5.x]Removing unnecessary `'` from modified type, variable name after escaping special characters 

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests - Added
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Review by NipunaRanasinghe — COMMENTED** [review]
@lnash94 Do we have diagnostics tests to verify that we'll not have compilation issues after removing the quote in all these cases?

**Comment by lnash94** [comment]
> @lnash94 Do we have diagnostics tests to verify that we'll not have compilation issues after removing the quote in all these cases?

We haven't added diagnostic test improvements to branches 1.5.x, 1.6.x, and 1.7.x. We have only included these improvements in the master branch. Therefore, I have added unit tests as usual to these branches and enabled diagnostic tests for the master branch. Are we planning to backport these test improvements (https://github.com/ballerina-platform/openapi-tools/pull/1418) to the 1.5.x, 1.6.x, and 1.7.x branches?

**Comment by NipunaRanasinghe** [comment]
> > @lnash94 Do we have diagnostics tests to verify that we'll not have compilation issues after removing the quote in all these cases?
> 
> We haven't added diagnostic test improvements to branches 1.5.x, 1.6.x, and 1.7.x. We have only included these improvements in the master branch. Therefore, I have added unit tests as usual to these branches and enabled diagnostic tests for the master branch. Are we planning to backport these test improvements (#1418) to the 1.5.x, 1.6.x, and 1.7.x branches?

The issue is, unit tests we've added here won't cover any compilation issues which can be introduced with these changes. anyway lets proceed with the unit tests for now as we can backport the service diagnostics tests as a separate effort anyway

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

**Pull request merged**
